### ISSUE TITLE
Extension doesn't work in VSCodium

### ISSUE THREAD

**Issue by pm4rcin** [KreativJos/csharpextensions#37] opened 2021-09-13 20:45 UTC
Hi, when I try to create a class, controller or any other thing from submenu it can't because "Weird, but the extension you are currently using could not be found".
OS: EndeavourOS 5.14.2-arch1-2
VSCodium: 1.60 (but the same thing happened with previous versions)
C# Extensions: v1.4.2

**Comment by KreativJos** [comment] 2021-09-20 15:55
Thank you for reporting this.
The issue is obvious, and it is kind of stupid I did not think of this before publishing:

https://github.com/KreativJos/csharpextensions/blob/master/src/extension.ts#L84:L87

The templates are loaded via the extension folder, which is resolved by the extension name. But the publishing name for vscodium is different, so it cannot be found.

I'll try to resolve this.

**Closed** 2021-09-20 19:01 UTC
Labels: bug

**Comment by pm4rcin** [comment] 2021-09-20 19:12
It works! Thanks :)
