### ISSUE TITLE
Fix pls.

### ISSUE THREAD

**Issue by shmellyorc** [KreativJos/csharpextensions#82] opened 2022-04-19 08:46 UTC
I get this now whenever I try to create a new class. In the past it was working great. Why mess with it.

Anywho this is when I try to make a new class. This is from veresion 1.6.1: 
![image](https://user-images.githubusercontent.com/5901214/163962853-90e6524b-c533-44e1-aa46-e133686a3e96.png)

**Comment by KreativJos** [comment] 2022-04-19 13:09
Duplicate of #79 
Already fixed, but not released yet.

**Closed by KreativJos** 2022-04-19 13:09 UTC

**Comment by KreativJos** [comment] 2022-04-19 21:47
Fixed version has been published (1.6.2).
