### ISSUE TITLE
RootNamespace detection Option

### ISSUE THREAD

**Issue by mz-zmsoft** [KreativJos/csharpextensions#15] opened 2020-07-04 06:18 UTC
Hey guys,

please implement a configuration for RootNamespace detection. All my (50+) repositories are organized in a structure like that:
```
+ [src]
        + [ProjectName]
             - Program.cs
             - ProjectName.csproj
        - ProjectName.sln
```

When creating a new c# File in Folder "ProjectName" the Namespace is always set to **src.ProjectName**. In the past, this repositories worked perfectly and the extension detected the correct Namespace **ProjectName**.

This issues forces me to add the RootNameSpace Tag in every csproj file in all my repositories! Please solve this! 

regards,
marcel

**Comment by PoLaKoSz** [comment] 2020-07-04 09:59
I was able to reproduce the issue. In the previous implementation the namespace detection only cared about the path of the `csproj` file not the content in it (line 110).
https://github.com/KreativJos/csharpextensions/blob/2fd8a99eb72b1aed8cb111a4cc0f3afbb10dfa6e/src/extension.ts#L102-L114
 If i am correct the `project.json` file is already deprecated so just changing the **namespaceDetector.ts** will fix this issue:
``` diff
private async fromCsproj(): Promise<string | undefined> {
    const csprojs: string[] = await findupglob('*.csproj', { cwd: path.dirname(this.filePath) });
    if (csprojs === null || csprojs.length < 1) {
        return undefined;
    }

    const csprojFile = csprojs[0];
    const fileContent = await this.read(Uri.file(csprojFile));
-   const rootNamespace = new CsprojReader(fileContent).getRootNamespace();
+   let rootNamespace = new CsprojReader(fileContent).getRootNamespace();
    if (rootNamespace === undefined) {
-       return undefinied;
+       rootNamespace = path.basename(path.dirname(csprojFile));
    }

    return this.calculateFullNamespace(rootNamespace, path.dirname(csprojFile));
}
```

**Comment by KreativJos** [comment] 2020-08-06 21:42
This is fixed in branch `bug/rootNamespaceSubfolder`.
Is it possible to write a test for this situation?

**Comment by KreativJos** [comment] 2020-08-06 22:08
And if someone would create a setting for this, that would be fine by me either way. But the way in the given branch seems to be a fine default.

**Comment by PoLaKoSz** [comment] 2020-08-25 19:18
I guess writing tests are possible ( https://code.visualstudio.com/api/working-with-extensions/testing-extension ).

**Comment by KreativJos** [comment] 2021-05-21 10:06
The branch has been merged.
Tests should be created for this, but I can't see how currently (because of files & paths in tests).

**Closed** 2021-09-29 08:33 UTC
Labels: tests
